In [1]:
print("Hola Mundo")

Hola Mundo

## Pasos 
1. Conexion a Mysql con python
2. Extraccion de tablas
3. Unir tablas (merge)
4. Limpiar y transformar datos
5. Guardar datos csv/mysql

In [2]:
!pip install pandas==2.3.3 sqlalchemy pymysql python-dotenv

Collecting pandas==2.3.3
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Collecting numpy>=1.26.0 (from pandas==2.3.3)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas==2.3.3) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas==2.3.3)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas==2.3.3) (2025.2)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/codespace/.local/lib/python3.12/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.3.3) (1.17.0)
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 22.9 MB/s  0:00:00m0:00:010:01
Downloading sqlalchemy-2.0.49-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 31.5 MB/s  0:00:00
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Downloading greenlet-3.3.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (613 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.9/613.9 kB 20.1 MB/s  0:00:00
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 34.7 MB/s  0:00:006m0:00:01
Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Installing collected packages: pytz, python-dotenv, pymysql, numpy, greenlet, sqlalchemy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [pandas]2m6/7 [pandas]emy]
Successfully installed greenlet-3.3.2 numpy-2.4.4 pandas-2.3.3 pymysql-1.1.2 python-dotenv-1.2.2 pytz-2026.1.post1 sqlalchemy-2.0.49

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [7]:
!pip install mysqlclient==2.2.4

Collecting mysqlclient==2.2.4
  Downloading mysqlclient-2.2.4.tar.gz (90 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: mysqlclient
  Building wheel for mysqlclient (pyproject.toml) ... done
  Created wheel for mysqlclient: filename=mysqlclient-2.2.4-cp312-cp312-linux_x86_64.whl size=133328 sha256=9d900ab26fb6af736c830d160053846e774a6bf93a2b071b53f6403cdded9c06
  Stored in directory: /home/codespace/.cache/pip/wheels/20/6f/c3/3b23bb01988b1c0bea0668e2116315ce43ced2179724ab593e
Successfully built mysqlclient
Installing collected packages: mysqlclient
Successfully installed mysqlclient-2.2.4

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [13]:
!pip install cryptography

Collecting cryptography
  Downloading cryptography-46.0.6-cp311-abi3-manylinux_2_34_x86_64.whl.metadata (5.7 kB)
Requirement already satisfied: cffi>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography) (2.23)
Downloading cryptography-46.0.6-cp311-abi3-manylinux_2_34_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 20.6 MB/s  0:00:00m0:00:01
Installing collected packages: cryptography
Successfully installed cryptography-46.0.6

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [27]:
DB_USER = 'root'
DB_PASSWORD = 'root'
DB_HOST = '10.0.11.46'
DB_PORT = '3310'
DB_NAME = 'retail_db'

MYSQL_URL = f"mysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

engine = create_engine(MYSQL_URL)

In [30]:
df_customers = pd.read_sql("SELECT * FROM customers",engine)

In [33]:
def extract_table(table_name: str) -> pd.DataFrame:
    
    query = f"SELECT * FROM {table_name}"

    try:
        df = pd.read_sql(query, engine)
        print(f"La tabla {table_name} se ha leido exitosamente")
    except Exception as e:
        print(f"Error al leer la tabla {table_name}: {e}")

    return df

In [41]:
df_customers = extract_table('customers')
df_orders = extract_table('orders')
df_order_items = extract_table('order_items')
df_products = extract_table('products')
df_categories = extract_table('categories')
df_departments = extract_table('departments')

La tabla customers se ha leido exitosamente
La tabla orders se ha leido exitosamente
La tabla order_items se ha leido exitosamente
La tabla products se ha leido exitosamente
La tabla categories se ha leido exitosamente
La tabla departments se ha leido exitosamente

In [37]:
df_customers.head()

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
2,3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,00725
3,4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
4,5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,00725

In [38]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12435 entries, 0 to 12434
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        12435 non-null  int64
 1   customer_fname     12435 non-null  object
 2   customer_lname     12435 non-null  object
 3   customer_email     12435 non-null  object
 4   customer_password  12435 non-null  object
 5   customer_street    12435 non-null  object
 6   customer_city      12435 non-null  object
 7   customer_state     12435 non-null  object
 8   customer_zipcode   12435 non-null  object
dtypes: int64(1), object(8)
memory usage: 874.5+ KB

In [39]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68883 entries, 0 to 68882
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           68883 non-null  int64
 1   order_date         68883 non-null  datetime64[ns]
 2   order_customer_id  68883 non-null  int64
 3   order_status       68883 non-null  object
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 2.1+ MB

In [42]:
df_orders['order_date'] = pd.to_datetime(df_orders['order_date'], errors = 'coerce')
df_orders.head()

   order_id order_date  order_customer_id     order_status
0         1 2013-07-25              11599           CLOSED
1         2 2013-07-25                256  PENDING_PAYMENT
2         3 2013-07-25              12111         COMPLETE
3         4 2013-07-25               8827           CLOSED
4         5 2013-07-25              11318         COMPLETE

In [44]:
df_customers['customer_full_name'] = (
    df_customers['customer_fname'].str.strip() + ' ' + df_customers['customer_lname'].str.strip()
)
df_customers['customer_full_name']

0        Richard Hernandez
1             Mary Barrett
2                Ann Smith
3               Mary Jones
4            Robert Hudson
               ...
12430            Mary Rios
12431         Angela Smith
12432      Benjamin Garcia
12433           Mary Mills
12434         Laura Horton
Name: customer_full_name, Length: 12435, dtype: object

In [46]:
# Joins

df = df_orders.merge(
    df_customers, left_on='order_customer_id', right_on= 'customer_id', how='left'
)

df.shape

(68883, 14)

In [47]:
df = df.merge(
    df_order_items, left_on='order_id', right_on='order_item_order_id', how='inner'
)

df.shape

(172198, 20)

In [48]:
df = df.merge(
    df_products, left_on='order_item_product_id', right_on='product_id', how='left'
)

In [49]:
df = df.merge(
    df_categories, left_on='product_category_id', right_on='category_id', how='left'
)

In [50]:
df = df.merge(
    df_departments, left_on='category_department_id', right_on='department_id', how='left'
)

In [51]:
df.head()

,order_id,order_date,order_customer_id,order_status,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,...,product_category_id,product_name,product_description,product_price,product_image,category_id,category_department_id,category_name,department_id,department_name
0,1,2013-07-25,11599,CLOSED,11599,Mary,Malone,XXXXXXXXX,XXXXXXXXX,8708 Indian Horse Highway,...,43,Diamondback Women's Serene Classic Comfort Bi,,299.98,http://images.acmesports.sports/Diamondback+Wo...,43,7,Camping & Hiking,7,Fan Shop
1,2,2013-07-25,256,PENDING_PAYMENT,256,David,Rodriguez,XXXXXXXXX,XXXXXXXXX,7605 Tawny Horse Falls,...,48,Pelican Sunstream 100 Kayak,,199.99,http://images.acmesports.sports/Pelican+Sunstr...,48,7,Water Sports,7,Fan Shop
2,2,2013-07-25,256,PENDING_PAYMENT,256,David,Rodriguez,XXXXXXXXX,XXXXXXXXX,7605 Tawny Horse Falls,...,24,Nike Men's Dri-FIT Victory Golf Polo,,50.00,http://images.acmesports.sports/Nike+Men%27s+D...,24,5,Women's Apparel,5,Golf
3,2,2013-07-25,256,PENDING_PAYMENT,256,David,Rodriguez,XXXXXXXXX,XXXXXXXXX,7605 Tawny Horse Falls,...,18,Nike Men's CJ Elite 2 TD Football Cleat,,129.99,http://images.acmesports.sports/Nike+Men%27s+C...,18,4,Men's Footwear,4,Apparel
4,4,2013-07-25,8827,CLOSED,8827,Brian,Wilson,XXXXXXXXX,XXXXXXXXX,8396 High Corners,...,40,Team Golf New England Patriots Putter Grip,,24.99,http://images.acmesports.sports/Team+Golf+New+...,40,6,Accessories,6,Outdoors

In [52]:
sales_detail = df[[
    'order_id',
    'order_date',
    'order_status',
    'customer_id',
    'customer_full_name',
    'customer_email',
    'customer_city',
    'customer_state',
    'product_id',
    'product_name',
    'category_name',
    'department_name',
    'order_item_quantity',
    'order_item_product_price',
    'order_item_subtotal'
]].copy()

sales_detail.head()

,order_id,order_date,order_status,customer_id,customer_full_name,customer_email,customer_city,customer_state,product_id,product_name,category_name,department_name,order_item_quantity,order_item_product_price,order_item_subtotal
0,1,2013-07-25,CLOSED,11599,Mary Malone,XXXXXXXXX,Hickory,NC,957,Diamondback Women's Serene Classic Comfort Bi,Camping & Hiking,Fan Shop,1,299.98,299.98
1,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,1073,Pelican Sunstream 100 Kayak,Water Sports,Fan Shop,1,199.99,199.99
2,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,5,50.00,250.00
3,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,403,Nike Men's CJ Elite 2 TD Football Cleat,Men's Footwear,Apparel,1,129.99,129.99
4,4,2013-07-25,CLOSED,8827,Brian Wilson,XXXXXXXXX,San Antonio,TX,897,Team Golf New England Patriots Putter Grip,Accessories,Outdoors,2,24.99,49.98

In [53]:
sales_detail.rename(columns={
    'order_id': 'sale_id',
    'order_date': 'sale_date',
    'order_status': 'sale_status',
    'customer_full_name': 'customer_name',
    'order_item_quantity': 'quantity',
    'order_item_product_price': 'unit_price',
    'order_item_subtotal': 'subtotal'
}, inplace=True)

sales_detail.head()

,sale_id,sale_date,sale_status,customer_id,customer_name,customer_email,customer_city,customer_state,product_id,product_name,category_name,department_name,quantity,unit_price,subtotal
0,1,2013-07-25,CLOSED,11599,Mary Malone,XXXXXXXXX,Hickory,NC,957,Diamondback Women's Serene Classic Comfort Bi,Camping & Hiking,Fan Shop,1,299.98,299.98
1,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,1073,Pelican Sunstream 100 Kayak,Water Sports,Fan Shop,1,199.99,199.99
2,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,5,50.00,250.00
3,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,403,Nike Men's CJ Elite 2 TD Football Cleat,Men's Footwear,Apparel,1,129.99,129.99
4,4,2013-07-25,CLOSED,8827,Brian Wilson,XXXXXXXXX,San Antonio,TX,897,Team Golf New England Patriots Putter Grip,Accessories,Outdoors,2,24.99,49.98

In [54]:
sales_detail['year'] = sales_detail['sale_date'].dt.year
sales_detail['month'] = sales_detail['sale_date'].dt.month
sales_detail['month_name'] = sales_detail['sale_date'].dt.month_name()

sales_detail[['sale_date', 'year', 'month', 'month_name']].head()

   sale_date  year  month month_name
0 2013-07-25  2013      7       July
1 2013-07-25  2013      7       July
2 2013-07-25  2013      7       July
3 2013-07-25  2013      7       July
4 2013-07-25  2013      7       July

In [55]:
sales_detail['customer_name'] = sales_detail['customer_name'].fillna('Cliente desconocido')
sales_detail['product_name'] = sales_detail['product_name'].fillna('Producto desconocido')
sales_detail['category_name'] = sales_detail['category_name'].fillna('Sin categoría')
sales_detail['department_name'] = sales_detail['department_name'].fillna('Sin departamento')

sales_detail.head()

,sale_id,sale_date,sale_status,customer_id,customer_name,customer_email,customer_city,customer_state,product_id,product_name,category_name,department_name,quantity,unit_price,subtotal,year,month,month_name
0,1,2013-07-25,CLOSED,11599,Mary Malone,XXXXXXXXX,Hickory,NC,957,Diamondback Women's Serene Classic Comfort Bi,Camping & Hiking,Fan Shop,1,299.98,299.98,2013,7,July
1,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,1073,Pelican Sunstream 100 Kayak,Water Sports,Fan Shop,1,199.99,199.99,2013,7,July
2,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,5,50.00,250.00,2013,7,July
3,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,403,Nike Men's CJ Elite 2 TD Football Cleat,Men's Footwear,Apparel,1,129.99,129.99,2013,7,July
4,4,2013-07-25,CLOSED,8827,Brian Wilson,XXXXXXXXX,San Antonio,TX,897,Team Golf New England Patriots Putter Grip,Accessories,Outdoors,2,24.99,49.98,2013,7,July

In [56]:
sales_detail = sales_detail.dropna(subset=['sale_id', 'sale_date', 'product_id'])
sales_detail.shape

(172198, 18)

In [57]:
sales_detail.head()

,sale_id,sale_date,sale_status,customer_id,customer_name,customer_email,customer_city,customer_state,product_id,product_name,category_name,department_name,quantity,unit_price,subtotal,year,month,month_name
0,1,2013-07-25,CLOSED,11599,Mary Malone,XXXXXXXXX,Hickory,NC,957,Diamondback Women's Serene Classic Comfort Bi,Camping & Hiking,Fan Shop,1,299.98,299.98,2013,7,July
1,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,1073,Pelican Sunstream 100 Kayak,Water Sports,Fan Shop,1,199.99,199.99,2013,7,July
2,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,502,Nike Men's Dri-FIT Victory Golf Polo,Women's Apparel,Golf,5,50.00,250.00,2013,7,July
3,2,2013-07-25,PENDING_PAYMENT,256,David Rodriguez,XXXXXXXXX,Chicago,IL,403,Nike Men's CJ Elite 2 TD Football Cleat,Men's Footwear,Apparel,1,129.99,129.99,2013,7,July
4,4,2013-07-25,CLOSED,8827,Brian Wilson,XXXXXXXXX,San Antonio,TX,897,Team Golf New England Patriots Putter Grip,Accessories,Outdoors,2,24.99,49.98,2013,7,July

In [58]:
sales_detail.to_csv('sales_detail.csv', index=False, encoding = 'utf-8')

In [62]:
df = pd.read_sql('SHOW TABLES', engine)
df

  Tables_in_retail_db
0          categories
1           customers
2         departments
3         order_items
4              orders
5            products
6        sales_detail

In [61]:
sales_detail.to_sql('sales_detail', engine, if_exists='replace', index=False)

172198